# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 787)
        MainWindow.setStyleSheet("background-color: rgb(122, 0, 60);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"border-style: outset;\n"
"border-width: 4px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_mul = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mul.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_mul.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 3, 3, 1, 1)
        self.pushButton_n8 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n8.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n8.setFont(font)
        self.pushButton_n8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n8.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.gridLayout.addWidget(self.pushButton_n8, 3, 1, 1, 1)
        self.pushButton_n6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n6.setFont(font)
        self.pushButton_n6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n6.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout.addWidget(self.pushButton_n6, 4, 2, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 5, 3, 1, 1)
        self.pushButton_stock = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_stock.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stock.setFont(font)
        self.pushButton_stock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stock.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/stock1.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_stock.setText("")
        self.pushButton_stock.setObjectName("pushButton_stock")
        self.gridLayout.addWidget(self.pushButton_stock, 0, 2, 1, 1)
        self.pushButton_alg = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_alg.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_alg.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_alg.setFont(font)
        self.pushButton_alg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_alg.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/alg1.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_alg.setText("")
        self.pushButton_alg.setObjectName("pushButton_alg")
        self.gridLayout.addWidget(self.pushButton_alg, 0, 1, 1, 1)
        self.pushButton_n5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n5.setFont(font)
        self.pushButton_n5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n5.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout.addWidget(self.pushButton_n5, 4, 1, 1, 1)
        self.pushButton_n0 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n0.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n0.setFont(font)
        self.pushButton_n0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n0.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.gridLayout.addWidget(self.pushButton_n0, 6, 0, 1, 1)
        self.pushButton_n2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n2.setFont(font)
        self.pushButton_n2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n2.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout.addWidget(self.pushButton_n2, 5, 1, 1, 1)
        self.pushButton_n1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n1.setFont(font)
        self.pushButton_n1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n1.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout.addWidget(self.pushButton_n1, 5, 0, 1, 1)
        self.pushButton_ac = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_ac.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ac.setFont(font)
        self.pushButton_ac.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ac.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"    color: #f4433;\n"
"}\n"
"")
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.gridLayout.addWidget(self.pushButton_ac, 2, 0, 1, 1)
        self.pushButton_n4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n4.setFont(font)
        self.pushButton_n4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n4.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout.addWidget(self.pushButton_n4, 4, 0, 1, 1)
        self.pushButton_n7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n7.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n7.setFont(font)
        self.pushButton_n7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n7.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout.addWidget(self.pushButton_n7, 3, 0, 1, 1)
        self.pushButton_sub = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_sub.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sub.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 4, 3, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_div.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_div.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 2, 3, 1, 1)
        self.pushButton_n9 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n9.setFont(font)
        self.pushButton_n9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n9.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.gridLayout.addWidget(self.pushButton_n9, 3, 2, 1, 1)
        self.pushButton_mr = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mr.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_mr.setFont(font)
        self.pushButton_mr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_mr.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"   color: #FFC10;\n"
"}")
        self.pushButton_mr.setObjectName("pushButton_mr")
        self.gridLayout.addWidget(self.pushButton_mr, 2, 2, 1, 1)
        self.pushButton_pc = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_pc.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_pc.setFont(font)
        self.pushButton_pc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pc.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_pc.setObjectName("pushButton_pc")
        self.gridLayout.addWidget(self.pushButton_pc, 6, 1, 1, 1)
        self.pushButton_n3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_n3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_n3.setFont(font)
        self.pushButton_n3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_n3.setStyleSheet("background-color: rgb(94, 106, 113);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #1976D;\n"
"}")
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout.addWidget(self.pushButton_n3, 5, 2, 1, 1)
        self.pushButton_convert = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_convert.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_convert.setFont(font)
        self.pushButton_convert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_convert.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/conv1.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_convert.setText("")
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.gridLayout.addWidget(self.pushButton_convert, 0, 0, 1, 1)
        self.pushButton_credits = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_credits.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_credits.setFont(font)
        self.pushButton_credits.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_credits.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/credit.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_credits.setText("")
        self.pushButton_credits.setObjectName("pushButton_credits")
        self.gridLayout.addWidget(self.pushButton_credits, 0, 3, 1, 1)
        self.pushButton_m = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_m.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_m.setFont(font)
        self.pushButton_m.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_m.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"   color: #FFC10;\n"
"}")
        self.pushButton_m.setObjectName("pushButton_m")
        self.gridLayout.addWidget(self.pushButton_m, 2, 1, 1, 1)
        self.pushButton_eq = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_eq.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_eq.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"QPushButton {\n"
"color: #4CAF5;\n"
"}")
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.gridLayout.addWidget(self.pushButton_eq, 6, 2, 1, 2)
        self.pushButton_health = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_health.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_health.setFont(font)
        self.pushButton_health.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_health.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/health.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_health.setText("")
        self.pushButton_health.setObjectName("pushButton_health")
        self.gridLayout.addWidget(self.pushButton_health, 1, 0, 1, 1)
        self.pushButton_gpa = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_gpa.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_gpa.setFont(font)
        self.pushButton_gpa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_gpa.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/gpa.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_gpa.setText("")
        self.pushButton_gpa.setObjectName("pushButton_gpa")
        self.gridLayout.addWidget(self.pushButton_gpa, 1, 1, 1, 1)
        self.pushButton_geo = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_geo.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_geo.setFont(font)
        self.pushButton_geo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_geo.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/geo.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_geo.setText("")
        self.pushButton_geo.setObjectName("pushButton_geo")
        self.gridLayout.addWidget(self.pushButton_geo, 1, 2, 1, 1)
        self.pushButton_bin = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_bin.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bin.setFont(font)
        self.pushButton_bin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bin.setStyleSheet("background-color: rgb(253, 191, 87);\n"
"border-image: url(:/newPrefix/bin.png);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.pushButton_bin.setText("")
        self.pushButton_bin.setObjectName("pushButton_bin")
        self.gridLayout.addWidget(self.pushButton_bin, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 417, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionAbout_Calculator = QtWidgets.QAction(MainWindow)
        self.actionAbout_Calculator.setObjectName("actionAbout_Calculator")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ultimate Calculator"))
        self.pushButton_mul.setText(_translate("MainWindow", "x"))
        self.pushButton_mul.setShortcut(_translate("MainWindow", "*"))
        self.pushButton_n8.setText(_translate("MainWindow", "8"))
        self.pushButton_n8.setShortcut(_translate("MainWindow", "8"))
        self.pushButton_n6.setText(_translate("MainWindow", "6"))
        self.pushButton_n6.setShortcut(_translate("MainWindow", "6"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_add.setShortcut(_translate("MainWindow", "+"))
        self.pushButton_n5.setText(_translate("MainWindow", "5"))
        self.pushButton_n5.setShortcut(_translate("MainWindow", "5"))
        self.pushButton_n0.setText(_translate("MainWindow", "0"))
        self.pushButton_n0.setShortcut(_translate("MainWindow", "0"))
        self.pushButton_n2.setText(_translate("MainWindow", "2"))
        self.pushButton_n2.setShortcut(_translate("MainWindow", "2"))
        self.pushButton_n1.setText(_translate("MainWindow", "1"))
        self.pushButton_n1.setShortcut(_translate("MainWindow", "1"))
        self.pushButton_ac.setText(_translate("MainWindow", "AC"))
        self.pushButton_ac.setShortcut(_translate("MainWindow", "Esc"))
        self.pushButton_n4.setText(_translate("MainWindow", "4"))
        self.pushButton_n4.setShortcut(_translate("MainWindow", "4"))
        self.pushButton_n7.setText(_translate("MainWindow", "7"))
        self.pushButton_n7.setShortcut(_translate("MainWindow", "7"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_sub.setShortcut(_translate("MainWindow", "-"))
        self.pushButton_div.setText(_translate("MainWindow", "÷"))
        self.pushButton_div.setShortcut(_translate("MainWindow", "/"))
        self.pushButton_n9.setText(_translate("MainWindow", "9"))
        self.pushButton_n9.setShortcut(_translate("MainWindow", "9"))
        self.pushButton_mr.setText(_translate("MainWindow", "MR"))
        self.pushButton_mr.setShortcut(_translate("MainWindow", "R"))
        self.pushButton_pc.setText(_translate("MainWindow", "."))
        self.pushButton_pc.setShortcut(_translate("MainWindow", "%"))
        self.pushButton_n3.setText(_translate("MainWindow", "3"))
        self.pushButton_n3.setShortcut(_translate("MainWindow", "3"))
        self.pushButton_m.setText(_translate("MainWindow", "M"))
        self.pushButton_m.setShortcut(_translate("MainWindow", "M"))
        self.pushButton_eq.setText(_translate("MainWindow", "="))
        self.pushButton_eq.setShortcut(_translate("MainWindow", "Return"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionAbout_Calculator.setText(_translate("MainWindow", "About Calculator"))
import uis.Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
